name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Linter
        run: npm run lint

      - name: Langium generate
        run: |
          HASH_BEFORE=$(sha1sum src/language-server/generated/* | sha1sum)
          
          npm run langium:generate
          
          HASH_AFTER=$(sha1sum src/language-server/generated/* | sha1sum)
          
          if [[ $HASH_BEFORE != $HASH_AFTER ]]; then
            echo "The generated code is not up to date."
            echo "Run 'npm run langium:generate' locally and commit the resulting generated code."
            exit 1
          fi

      - name: Build
        run: npm run build