name: Publish Interpreter

on:
  release:
    types: [created]

# https://docs.github.com/en/actions/guides/publishing-nodejs-packages
jobs:
  publish-interpreter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          always-auth: true
          registry-url: 'https://npm.pkg.github.com'
      - run: npm ci
      - name: Publish interpreter
        run: npx nx run interpreter:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
