name: Publish Packages

on:
  release:
    types: [created]

# https://docs.github.com/en/actions/guides/publishing-nodejs-packages
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          always-auth: true
          registry-url: 'https://npm.pkg.github.com'
      - run: npm ci
      - name: Publish interpreter
        run: npx nx run interpreter:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish language server web worker
        run: npx nx run language-server-web-worker:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish monaco editor
        run: npx nx run @jayvee/monaco-editor:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
